/** Static node type registry — fallback when backend is unavailable */

import type { NodeTypeRegistry } from '../api/client'

export const STATIC_REGISTRY: NodeTypeRegistry = {
  categories: {
    sources: { label: 'Audio Sources', color: '#A3E635' },
    processing: { label: 'Audio Processing', color: '#FBBF24' },
    telephony: { label: 'Telephony', color: '#E879F9' },
    network: { label: 'Network', color: '#F87171' },
    speech: { label: 'Speech', color: '#818CF8' },
    llm: { label: 'LLM', color: '#34D399' },
    evaluation: { label: 'Evaluation', color: '#FB923C' },
    output: { label: 'Output', color: '#94A3B8' },
  },
  node_types: {
    speech_source: {
      type_id: 'speech_source', label: 'Speech Source', category: 'sources', color: '#A3E635',
      description: 'Clean speech audio from corpus or PipelineInput',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'source_mode', type: 'select', label: 'Source', default: 'pipeline_input', options: [{ value: 'pipeline_input', label: 'From Test Case' }, { value: 'file', label: 'Audio File' }], description: '' },
      ],
    },
    noise_generator: {
      type_id: 'noise_generator', label: 'Noise Generator', category: 'sources', color: '#A3E635',
      description: 'Generate noise: white, pink, babble, traffic, wind',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'noise_type', type: 'select', label: 'Noise Type', default: 'pink_lpf', options: [{ value: 'white', label: 'White' }, { value: 'pink', label: 'Pink' }, { value: 'pink_lpf', label: 'Pink (LPF)' }, { value: 'babble', label: 'Babble' }, { value: 'traffic', label: 'Traffic' }, { value: 'wind', label: 'Wind' }, { value: 'hvac_fan', label: 'HVAC Fan' }, { value: 'secondary_voice', label: 'Secondary Voice' }, { value: 'silence', label: 'Silence' }], description: '' },
        { name: 'seed', type: 'number', label: 'Random Seed', default: null, description: 'Leave empty for random' },
      ],
    },
    audio_file: {
      type_id: 'audio_file', label: 'Audio File', category: 'sources', color: '#A3E635',
      description: 'Load audio from a WAV file',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: '' },
      ],
    },
    mixer: {
      type_id: 'mixer', label: 'Audio Mixer', category: 'processing', color: '#FBBF24',
      description: 'Mix N audio inputs at specified SNR levels',
      dynamic_inputs: true,
      inputs: [
        { name: 'audio_in_0', type: 'audio', required: true, description: 'Primary (speech)' },
        { name: 'audio_in_1', type: 'audio', required: false, description: 'Noise 1' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'snr_db', type: 'slider', label: 'SNR (dB)', default: 20, min: -10, max: 40, step: 1, description: '' },
        { name: 'mixing_mode', type: 'select', label: 'Mode', default: 'snr', options: [{ value: 'snr', label: 'SNR-calibrated' }, { value: 'equal', label: 'Equal gain' }], description: '' },
      ],
    },
    echo_simulator: {
      type_id: 'echo_simulator', label: 'Echo Simulator', category: 'processing', color: '#FBBF24',
      description: 'Simulate acoustic echo coupling path',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic input' },
        { name: 'speaker_in', type: 'audio', required: false, description: 'Speaker feedback' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'delay_ms', type: 'slider', label: 'Delay (ms)', default: 100, min: 0, max: 500, step: 10, description: '' },
        { name: 'gain_db', type: 'slider', label: 'Gain (dB)', default: -6, min: -60, max: 0, step: 1, description: '' },
      ],
    },
    eq_filter: {
      type_id: 'eq_filter', label: 'EQ Filter', category: 'processing', color: '#FBBF24',
      description: 'Biquad filter chain',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'filters', type: 'json', label: 'Filter Chain', default: [], description: '[{"type":"lpf","freq":8000,"q":0.707}]' },
      ],
    },
    gain: {
      type_id: 'gain', label: 'Gain', category: 'processing', color: '#FBBF24',
      description: 'Simple volume adjustment',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'gain_db', type: 'slider', label: 'Gain (dB)', default: 0, min: -60, max: 24, step: 0.5, description: '' },
      ],
    },
    audio_preprocess: {
      type_id: 'audio_preprocess', label: 'Audio Pre-Processing', category: 'processing', color: '#FBBF24',
      description: 'AEC, AGC, noise gate, VAD',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'enable_agc', type: 'boolean', label: 'Auto Gain Control', default: true, description: '' },
        { name: 'enable_noise_gate', type: 'boolean', label: 'Noise Gate', default: false, description: '' },
      ],
    },
    audio_postprocess: {
      type_id: 'audio_postprocess', label: 'Audio Post-Processing', category: 'processing', color: '#FBBF24',
      description: 'Normalization, limiting',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'normalize', type: 'boolean', label: 'Normalize', default: true, description: '' },
        { name: 'enable_limiter', type: 'boolean', label: 'Limiter', default: true, description: '' },
      ],
    },
    audio_buffer: {
      type_id: 'audio_buffer', label: 'Audio Buffer', category: 'processing', color: '#FBBF24',
      description: 'Chunk/buffer audio for streaming simulation',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'chunk_ms', type: 'slider', label: 'Chunk Size (ms)', default: 20, min: 5, max: 200, step: 5, description: '' },
      ],
    },
    network_sim: {
      type_id: 'network_sim', label: 'Network Simulator', category: 'network', color: '#F87171',
      description: 'Simulate network latency, jitter, packet loss',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: false, description: '' },
        { name: 'text_in', type: 'text', required: false, description: '' },
      ],
      outputs: [
        { name: 'audio_out', type: 'audio', required: false, description: '' },
        { name: 'text_out', type: 'text', required: false, description: '' },
      ],
      config_fields: [
        { name: 'latency_ms', type: 'slider', label: 'Latency (ms)', default: 50, min: 0, max: 2000, step: 10, description: '' },
        { name: 'jitter_ms', type: 'slider', label: 'Jitter (ms)', default: 10, min: 0, max: 500, step: 5, description: '' },
        { name: 'packet_loss_pct', type: 'slider', label: 'Packet Loss (%)', default: 0, min: 0, max: 50, step: 0.5, description: '' },
      ],
    },
    tts: {
      type_id: 'tts', label: 'Text-to-Speech', category: 'speech', color: '#818CF8',
      description: 'Convert text to audio',
      dynamic_inputs: false,
      inputs: [{ name: 'text_in', type: 'text', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'provider', type: 'select', label: 'Provider', default: 'edge', options: [{ value: 'openai', label: 'OpenAI' }, { value: 'elevenlabs', label: 'ElevenLabs' }, { value: 'edge', label: 'Edge (Free)' }, { value: 'piper', label: 'Piper (Local)' }], description: '' },
        { name: 'voice_id', type: 'string', label: 'Voice ID', default: '', description: '' },
      ],
    },
    stt: {
      type_id: 'stt', label: 'Speech-to-Text', category: 'speech', color: '#818CF8',
      description: 'Transcribe audio to text',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'text_out', type: 'text', required: false, description: '' }],
      config_fields: [
        { name: 'backend', type: 'select', label: 'Backend', default: 'whisper_local', options: [{ value: 'whisper_local', label: 'Whisper (Local)' }, { value: 'whisper_api', label: 'Whisper (API)' }, { value: 'deepgram', label: 'Deepgram' }], description: '' },
      ],
    },
    llm: {
      type_id: 'llm', label: 'LLM', category: 'llm', color: '#34D399',
      description: 'Request/response LLM (GPT-4o, Gemini, Claude, Ollama)',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: false, description: 'Audio input' },
        { name: 'text_in', type: 'text', required: false, description: 'Text input' },
      ],
      outputs: [
        { name: 'text_out', type: 'text', required: false, description: '' },
        { name: 'audio_out', type: 'audio', required: false, description: '' },
      ],
      config_fields: [
        { name: 'backend', type: 'select', label: 'Backend', default: 'openai:gpt-4o-audio-preview', options: [{ value: 'openai:gpt-4o-audio-preview', label: 'GPT-4o Audio' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-haiku-4-5-20251001', label: 'Claude Haiku' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'system_prompt', type: 'string', label: 'System Prompt', default: 'You are a helpful in-car voice assistant.', description: '' },
        { name: 'temperature', type: 'slider', label: 'Temperature', default: 0.7, min: 0, max: 2, step: 0.1, description: '' },
      ],
    },
    llm_realtime: {
      type_id: 'llm_realtime', label: 'LLM Realtime', category: 'llm', color: '#34D399',
      description: 'Streaming WebSocket LLM (OpenAI Realtime API)',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: 'Streaming audio' }],
      outputs: [
        { name: 'text_out', type: 'text', required: false, description: '' },
        { name: 'audio_out', type: 'audio', required: false, description: '' },
      ],
      config_fields: [
        { name: 'model', type: 'select', label: 'Model', default: 'gpt-4o-realtime-preview', options: [{ value: 'gpt-4o-realtime-preview', label: 'GPT-4o Realtime' }, { value: 'gpt-4o-mini-realtime-preview', label: 'GPT-4o Mini Realtime' }], description: '' },
        { name: 'voice', type: 'select', label: 'Voice', default: 'alloy', options: [{ value: 'alloy', label: 'Alloy' }, { value: 'echo', label: 'Echo' }, { value: 'shimmer', label: 'Shimmer' }, { value: 'ash', label: 'Ash' }, { value: 'coral', label: 'Coral' }, { value: 'sage', label: 'Sage' }], description: '' },
        { name: 'turn_detection', type: 'select', label: 'Turn Detection', default: 'server_vad', options: [{ value: 'server_vad', label: 'Server VAD' }, { value: 'manual', label: 'Manual' }], description: '' },
        { name: 'temperature', type: 'slider', label: 'Temperature', default: 0.8, min: 0, max: 2, step: 0.1, description: '' },
        { name: 'system_prompt', type: 'string', label: 'Instructions', default: 'You are a helpful in-car voice assistant.', description: '' },
      ],
    },
    telephony_codec: {
      type_id: 'telephony_codec', label: 'BT Codec', category: 'telephony', color: '#E879F9',
      description: 'Bluetooth codec simulation (CVSD narrowband / mSBC wideband)',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'codec_type', type: 'select', label: 'Codec', default: 'msbc', options: [{ value: 'cvsd', label: 'CVSD (8 kHz narrowband)' }, { value: 'msbc', label: 'mSBC (16 kHz wideband)' }, { value: 'none', label: 'None (bypass)' }], description: '' },
        { name: 'cvsd_snr_db', type: 'slider', label: 'CVSD SNR (dB)', default: 27, min: 20, max: 35, step: 1, description: 'Quantization noise floor for CVSD' },
        { name: 'msbc_snr_db', type: 'slider', label: 'mSBC SNR (dB)', default: 37, min: 30, max: 45, step: 1, description: 'Quantization noise floor for mSBC' },
      ],
    },
    aec: {
      type_id: 'aec', label: 'Echo Canceller', category: 'telephony', color: '#E879F9',
      description: 'Adaptive acoustic echo canceller (NLMS / RLS / Kalman)',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic signal (near-end + echo)' },
        { name: 'ref_in', type: 'audio', required: true, description: 'Far-end reference (speaker signal)' },
      ],
      outputs: [
        { name: 'audio_out', type: 'audio', required: false, description: 'Echo-cancelled signal' },
        { name: 'echo_est', type: 'audio', required: false, description: 'Estimated echo component' },
      ],
      config_fields: [
        { name: 'algorithm', type: 'select', label: 'Algorithm', default: 'nlms', options: [{ value: 'nlms', label: 'NLMS' }, { value: 'rls', label: 'RLS' }, { value: 'kalman', label: 'Kalman' }], description: '' },
        { name: 'filter_length_ms', type: 'slider', label: 'Filter Length (ms)', default: 200, min: 50, max: 500, step: 10, description: 'Adaptive filter tap length' },
        { name: 'step_size', type: 'slider', label: 'Step Size (mu)', default: 0.1, min: 0.01, max: 1, step: 0.01, description: 'NLMS learning rate' },
        { name: 'forgetting_factor', type: 'slider', label: 'Forgetting Factor', default: 0.999, min: 0.9, max: 1, step: 0.001, description: 'RLS lambda' },
      ],
    },
    aec_residual: {
      type_id: 'aec_residual', label: 'AEC Residual', category: 'telephony', color: '#E879F9',
      description: 'Simulate imperfect AEC: residual echo leakage + NLD artifacts',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic / AEC output signal' },
        { name: 'echo_ref', type: 'audio', required: false, description: 'Echo reference for residual' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'suppression_db', type: 'slider', label: 'Suppression (dB)', default: -25, min: -60, max: 0, step: 1, description: '-40=excellent AEC, -10=poor AEC' },
        { name: 'residual_type', type: 'select', label: 'Residual Type', default: 'mixed', options: [{ value: 'partial', label: 'Partial' }, { value: 'nonlinear', label: 'Non-linear (NLD)' }, { value: 'mixed', label: 'Mixed' }], description: '' },
        { name: 'nonlinear_distortion', type: 'slider', label: 'NLD Strength', default: 0.3, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    agc: {
      type_id: 'agc', label: 'AGC', category: 'telephony', color: '#E879F9',
      description: 'Automatic gain control with envelope follower and compression',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'preset', type: 'select', label: 'Preset', default: 'mild', options: [{ value: 'off', label: 'Off' }, { value: 'mild', label: 'Mild' }, { value: 'aggressive', label: 'Aggressive' }, { value: 'custom', label: 'Custom' }], description: '' },
        { name: 'target_rms_db', type: 'slider', label: 'Target RMS (dB)', default: -18, min: -30, max: 0, step: 1, description: '' },
        { name: 'attack_ms', type: 'slider', label: 'Attack (ms)', default: 50, min: 5, max: 500, step: 5, description: '' },
        { name: 'release_ms', type: 'slider', label: 'Release (ms)', default: 200, min: 20, max: 2000, step: 10, description: '' },
        { name: 'max_gain_db', type: 'slider', label: 'Max Gain (dB)', default: 30, min: 0, max: 40, step: 1, description: '' },
        { name: 'compression_ratio', type: 'slider', label: 'Compression Ratio', default: 4, min: 1, max: 20, step: 0.5, description: '' },
      ],
    },
    noise_reduction: {
      type_id: 'noise_reduction', label: 'Noise Reduction', category: 'telephony', color: '#E879F9',
      description: 'Speech enhancement via spectral subtraction or Wiener filtering',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: true, description: 'Noisy input' },
        { name: 'noise_ref', type: 'audio', required: false, description: 'Noise-only reference (optional)' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'method', type: 'select', label: 'Method', default: 'spectral_subtraction', options: [{ value: 'spectral_subtraction', label: 'Spectral Subtraction' }, { value: 'wiener', label: 'Wiener Filter' }], description: '' },
        { name: 'suppression_db', type: 'slider', label: 'Max Suppression (dB)', default: 12, min: 0, max: 30, step: 1, description: '' },
        { name: 'noise_floor_db', type: 'slider', label: 'Noise Floor (dB)', default: -60, min: -80, max: -20, step: 1, description: '' },
        { name: 'smoothing_factor', type: 'slider', label: 'Smoothing', default: 0.9, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    sample_rate_converter: {
      type_id: 'sample_rate_converter', label: 'Sample Rate Converter', category: 'telephony', color: '#E879F9',
      description: 'Polyphase sample rate conversion',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'target_sample_rate', type: 'select', label: 'Target Rate', default: '16000', options: [{ value: '8000', label: '8 kHz (narrowband)' }, { value: '16000', label: '16 kHz (wideband)' }, { value: '22050', label: '22.05 kHz' }, { value: '44100', label: '44.1 kHz (CD)' }, { value: '48000', label: '48 kHz' }], description: '' },
      ],
    },
    time_delay: {
      type_id: 'time_delay', label: 'Time Delay', category: 'telephony', color: '#E879F9',
      description: 'Standalone delay line',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'delay_ms', type: 'slider', label: 'Delay (ms)', default: 0, min: 0, max: 2000, step: 1, description: '' },
        { name: 'pad_mode', type: 'select', label: 'Mode', default: 'zero', options: [{ value: 'zero', label: 'Zero-pad (extends length)' }, { value: 'truncate', label: 'Truncate (maintain length)' }], description: '' },
      ],
    },
    doubletalk_metrics: {
      type_id: 'doubletalk_metrics', label: 'Doubletalk Metrics', category: 'telephony', color: '#E879F9',
      description: 'Compute ERLE, near-end distortion, and activity ratios',
      dynamic_inputs: false,
      inputs: [
        { name: 'near_end_clean', type: 'audio', required: true, description: 'Clean near-end reference' },
        { name: 'far_end_clean', type: 'audio', required: false, description: 'Clean far-end reference' },
        { name: 'mic_signal', type: 'audio', required: true, description: 'Mic signal (with echo)' },
        { name: 'aec_output', type: 'audio', required: false, description: 'AEC output signal' },
        { name: 'echo_ref', type: 'audio', required: false, description: 'Echo reference' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'frame_ms', type: 'slider', label: 'Frame Size (ms)', default: 20, min: 10, max: 40, step: 5, description: '' },
        { name: 'vad_threshold_db', type: 'slider', label: 'VAD Threshold (dB)', default: -40, min: -60, max: -20, step: 1, description: '' },
      ],
    },
    far_end_source: {
      type_id: 'far_end_source', label: 'Far-End Speech Source', category: 'sources', color: '#A3E635',
      description: 'Far-end caller audio with timing offset for 2-way telephony',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: 'Far-end speech signal' }],
      config_fields: [
        { name: 'source_mode', type: 'select', label: 'Source', default: 'pipeline_input', options: [{ value: 'pipeline_input', label: 'From Test Case' }, { value: 'corpus_entry', label: 'Corpus Entry' }, { value: 'file', label: 'Audio File' }], description: '' },
        { name: 'corpus_entry_id', type: 'string', label: 'Corpus Entry ID', default: '', description: '' },
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: '' },
        { name: 'level_db', type: 'slider', label: 'Level (dB)', default: 0, min: -30, max: 12, step: 0.5, description: 'Gain applied to far-end speech. 0=original level.' },
        { name: 'offset_ms', type: 'slider', label: 'Offset (ms)', default: 0, min: -5000, max: 5000, step: 50, description: 'Timing offset. Negative=far-end starts first (barge-in).' },
      ],
    },
    telephony_judge: {
      type_id: 'telephony_judge', label: 'Telephony Judge', category: 'evaluation', color: '#FB923C',
      description: 'LLM-based telephony quality evaluation with multi-judge voting',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: false, description: 'LLM response text' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Processed audio' },
        { name: 'near_end_ref', type: 'audio', required: false, description: 'Clean near-end reference' },
        { name: 'far_end_ref', type: 'audio', required: false, description: 'Clean far-end reference' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'modes', type: 'select', label: 'Evaluation Mode', default: 'auto', options: [{ value: 'auto', label: 'Auto-detect' }, { value: 'uplink_quality', label: 'Uplink Quality' }, { value: 'downlink_quality', label: 'Downlink Quality' }, { value: 'speaker_attribution', label: 'Speaker Attribution' }, { value: 'barge_in', label: 'Barge-in Detection' }, { value: 'conversational', label: 'Conversational Quality' }, { value: 'all', label: 'All Modes' }], description: '' },
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o-audio-preview', options: [{ value: 'openai:gpt-4o-audio-preview', label: 'GPT-4o Audio' }, { value: 'openai:gpt-4o-mini-audio-preview', label: 'GPT-4o Mini Audio' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }], description: '' },
        { name: 'num_judges', type: 'slider', label: 'Number of Judges', default: 3, min: 1, max: 7, step: 2, description: 'Odd number for majority voting' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'system_prompt_override', type: 'string', label: 'System Prompt Override', default: '', description: 'Override default telephony judge prompt' },
      ],
    },
    safety_critical_eval: {
      type_id: 'safety_critical_eval', label: 'Safety-Critical Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic safety evaluation: vehicle safety, personal safety, child safety, emergency protocol',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: 'Weighted average score threshold for pass' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: 'Any sub-agent below this = automatic fail' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: 'Original user query for context (optional)' },
      ],
    },
    compliance_eval: {
      type_id: 'compliance_eval', label: 'Compliance Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic compliance evaluation: legal, privacy, regulatory',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    trust_brand_eval: {
      type_id: 'trust_brand_eval', label: 'Trust & Brand Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic trust evaluation: misinformation, ethics/bias, brand safety',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    ux_quality_eval: {
      type_id: 'ux_quality_eval', label: 'UX Quality Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic UX evaluation: driver cognitive load, emotional intelligence',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    eval_analysis: {
      type_id: 'eval_analysis', label: 'Evaluation & Analysis', category: 'evaluation', color: '#FB923C',
      description: 'Combined evaluation engine',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text' },
        { name: 'audio_in', type: 'audio', required: false, description: 'LLM response audio' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'evaluators', type: 'select', label: 'Evaluators', default: 'command_match', options: [{ value: 'command_match', label: 'Command Match' }, { value: 'llm_judge', label: 'LLM Judge' }, { value: 'wer', label: 'WER' }, { value: 'all', label: 'All' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    text_output: {
      type_id: 'text_output', label: 'Text Output', category: 'output', color: '#94A3B8',
      description: 'Display text result',
      dynamic_inputs: false,
      inputs: [{ name: 'text_in', type: 'text', required: true, description: '' }],
      outputs: [],
      config_fields: [{ name: 'label', type: 'string', label: 'Label', default: 'Output', description: '' }],
    },
    audio_output: {
      type_id: 'audio_output', label: 'Audio Output', category: 'output', color: '#94A3B8',
      description: 'Save or play audio result',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [],
      config_fields: [{ name: 'label', type: 'string', label: 'Label', default: 'Output', description: '' }],
    },
    eval_output: {
      type_id: 'eval_output', label: 'Eval Output', category: 'output', color: '#94A3B8',
      description: 'Display evaluation results',
      dynamic_inputs: false,
      inputs: [{ name: 'eval_in', type: 'evaluation', required: true, description: '' }],
      outputs: [],
      config_fields: [{ name: 'label', type: 'string', label: 'Label', default: 'Results', description: '' }],
    },
  },
}
