/** Static node type registry — fallback when backend is unavailable */

import type { NodeTypeRegistry } from '../api/client'

export const STATIC_REGISTRY: NodeTypeRegistry = {
  categories: {
    sources: { label: 'Audio Sources', color: '#A3E635' },
    processing: { label: 'Audio Processing', color: '#FBBF24' },
    telephony: { label: 'Telephony', color: '#E879F9' },
    network: { label: 'Network', color: '#F87171' },
    speech: { label: 'Speech', color: '#818CF8' },
    llm: { label: 'LLM', color: '#34D399' },
    evaluation: { label: 'Evaluation', color: '#FB923C' },
    logic: { label: 'Logic', color: '#67E8F9' },
    output: { label: 'Output', color: '#94A3B8' },
  },
  node_types: {
    speech_source: {
      type_id: 'speech_source', label: 'Speech Source', category: 'sources', color: '#A3E635',
      description: 'Plays corpus samples (random from category if none specified), pre-recorded samples, or files',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'source_mode', type: 'select', label: 'Source', default: 'corpus_entry', options: [{ value: 'pipeline_input', label: 'From Test Case' }, { value: 'corpus_entry', label: 'Corpus Entry (TTS)' }, { value: 'speech_sample', label: 'Pre-recorded Sample' }, { value: 'file', label: 'Audio File' }], description: '' },
        { name: 'corpus_category', type: 'select', label: 'Corpus Category', default: '', options: [{ value: '', label: 'Any (random)' }, { value: 'harvard_sentence', label: 'Harvard Sentences' }, { value: 'navigation', label: 'Navigation' }, { value: 'media', label: 'Media Control' }, { value: 'climate', label: 'Climate Control' }, { value: 'phone', label: 'Phone' }, { value: 'general', label: 'General' }, { value: 'direct_harm', label: 'Direct Harm (Adversarial)' }, { value: 'jailbreak', label: 'Jailbreak (Adversarial)' }], description: 'Random sample each run if no specific entry set' },
        { name: 'corpus_entry_id', type: 'string', label: 'Specific Entry ID', default: '', description: 'Leave blank to randomize from category' },
        { name: 'speech_sample_id', type: 'string', label: 'Speech Sample ID', default: '', description: 'UUID of pre-recorded sample' },
        { name: 'voice_id', type: 'string', label: 'Voice ID', default: '', description: 'Voice for TTS synthesis' },
        { name: 'tts_provider', type: 'select', label: 'TTS Provider', default: 'edge', options: [{ value: 'edge', label: 'Edge (Free)' }, { value: 'openai', label: 'OpenAI' }, { value: 'google', label: 'Google' }, { value: 'elevenlabs', label: 'ElevenLabs' }, { value: 'piper', label: 'Piper (Local)' }, { value: 'azure', label: 'Azure' }], description: '' },
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: 'Path to WAV file' },
        { name: 'level_db', type: 'slider', label: 'Level (dB)', default: 0, min: -30, max: 12, step: 0.5, description: 'Gain applied to source audio' },
      ],
    },
    noise_generator: {
      type_id: 'noise_generator', label: 'Noise Generator', category: 'sources', color: '#A3E635',
      description: 'Synthetic noise, car cabin recordings, or noise files',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'noise_type', type: 'select', label: 'Noise Type', default: 'pink_lpf', options: [{ value: 'white', label: 'White' }, { value: 'pink', label: 'Pink' }, { value: 'pink_lpf', label: 'Pink (LPF)' }, { value: 'babble', label: 'Babble' }, { value: 'traffic', label: 'Traffic' }, { value: 'wind', label: 'Wind' }, { value: 'hvac_fan', label: 'HVAC Fan' }, { value: 'secondary_voice', label: 'Secondary Voice' }, { value: 'silence', label: 'Silence' }, { value: 'car_noise', label: 'Car Noise (from library)' }, { value: 'file', label: 'Noise File (WAV)' }], description: '' },
        { name: 'car_id', type: 'string', label: 'Car ID', default: '', description: 'UUID of car profile — browse at /browser' },
        { name: 'car_noise_category', type: 'select', label: 'Car Noise Category', default: 'road', options: [{ value: 'road', label: 'Road Noise' }, { value: 'fan', label: 'HVAC Fan' }], description: '' },
        { name: 'car_speed', type: 'slider', label: 'Speed / Fan Level', default: 30, min: 0, max: 80, step: 5, description: 'MPH for road, 0-10 for fan' },
        { name: 'noise_file_path', type: 'string', label: 'Noise File Path', default: '', description: 'Path to WAV noise file' },
        { name: 'seed', type: 'number', label: 'Random Seed', default: null, description: 'Leave empty for random' },
        { name: 'duration_s', type: 'number', label: 'Duration (s)', default: 0, description: '0 = match speech source length' },
      ],
    },
    audio_file: {
      type_id: 'audio_file', label: 'Audio File', category: 'sources', color: '#A3E635',
      description: 'Load audio from a WAV file',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: '' },
      ],
    },
    mixer: {
      type_id: 'mixer', label: 'Audio Mixer', category: 'processing', color: '#FBBF24',
      description: 'Mix N audio inputs with per-channel gain and master output',
      dynamic_inputs: true,
      inputs: [
        { name: 'audio_in_0', type: 'audio', required: true, description: 'Input 1' },
        { name: 'audio_in_1', type: 'audio', required: false, description: 'Input 2' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'gain_0_db', type: 'slider', label: 'Input 1 Gain (dB)', default: 0, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'gain_1_db', type: 'slider', label: 'Input 2 Gain (dB)', default: 0, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'gain_2_db', type: 'slider', label: 'Input 3 Gain (dB)', default: -100, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'gain_3_db', type: 'slider', label: 'Input 4 Gain (dB)', default: -100, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'gain_4_db', type: 'slider', label: 'Input 5 Gain (dB)', default: -100, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'gain_5_db', type: 'slider', label: 'Input 6 Gain (dB)', default: -100, min: -100, max: 10, step: 0.5, description: '' },
        { name: 'master_gain_db', type: 'slider', label: 'Master Output (dB)', default: 0, min: -100, max: 10, step: 0.5, description: '' },
      ],
    },
    echo_simulator: {
      type_id: 'echo_simulator', label: 'Echo Simulator', category: 'processing', color: '#FBBF24',
      description: 'Simulate acoustic echo coupling path',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic input' },
        { name: 'speaker_in', type: 'audio', required: false, description: 'Speaker feedback' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'delay_ms', type: 'slider', label: 'Delay (ms)', default: 100, min: 0, max: 500, step: 10, description: '' },
        { name: 'gain_db', type: 'slider', label: 'Gain (dB)', default: -6, min: -60, max: 0, step: 1, description: '' },
      ],
    },
    eq_filter: {
      type_id: 'eq_filter', label: 'EQ Filter', category: 'processing', color: '#FBBF24',
      description: 'Biquad filter chain',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'filters', type: 'json', label: 'Filter Chain', default: [], description: '[{"type":"lpf","freq":8000,"q":0.707}]' },
      ],
    },
    gain: {
      type_id: 'gain', label: 'Gain', category: 'processing', color: '#FBBF24',
      description: 'Simple volume adjustment',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'gain_db', type: 'slider', label: 'Gain (dB)', default: 0, min: -60, max: 24, step: 0.5, description: '' },
      ],
    },
    audio_buffer: {
      type_id: 'audio_buffer', label: 'Audio Buffer', category: 'processing', color: '#FBBF24',
      description: 'Chunk/buffer audio for streaming simulation',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'chunk_ms', type: 'slider', label: 'Chunk Size (ms)', default: 20, min: 5, max: 200, step: 5, description: '' },
      ],
    },
    network_sim: {
      type_id: 'network_sim', label: 'Network Simulator', category: 'network', color: '#F87171',
      description: 'Simulate network latency, jitter, packet loss',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: false, description: '' },
        { name: 'text_in', type: 'text', required: false, description: '' },
      ],
      outputs: [
        { name: 'audio_out', type: 'audio', required: false, description: '' },
        { name: 'text_out', type: 'text', required: false, description: '' },
      ],
      config_fields: [
        { name: 'latency_ms', type: 'slider', label: 'Latency (ms)', default: 50, min: 0, max: 2000, step: 10, description: '' },
        { name: 'jitter_ms', type: 'slider', label: 'Jitter (ms)', default: 10, min: 0, max: 500, step: 5, description: '' },
        { name: 'packet_loss_pct', type: 'slider', label: 'Packet Loss (%)', default: 0, min: 0, max: 50, step: 0.5, description: '' },
      ],
    },
    tts: {
      type_id: 'tts', label: 'Text-to-Speech', category: 'speech', color: '#818CF8',
      description: 'Convert text to audio using a TTS provider',
      dynamic_inputs: false,
      inputs: [{ name: 'text_in', type: 'text', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'provider', type: 'select', label: 'Provider', default: 'edge', options: [{ value: 'openai', label: 'OpenAI' }, { value: 'google', label: 'Google Cloud' }, { value: 'elevenlabs', label: 'ElevenLabs' }, { value: 'azure', label: 'Azure' }, { value: 'edge', label: 'Edge (Free)' }, { value: 'gtts', label: 'gTTS (Free)' }, { value: 'piper', label: 'Piper (Local)' }, { value: 'coqui', label: 'Coqui (Local)' }, { value: 'bark', label: 'Bark (Local)' }, { value: 'espeak', label: 'eSpeak (System)' }], description: '' },
        { name: 'voice_id', type: 'string', label: 'Voice ID', default: '', description: 'Provider-specific voice ID. Browse at /settings.' },
        { name: 'language', type: 'select', label: 'Language', default: 'en', options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }, { value: 'it', label: 'Italian' }, { value: 'pt', label: 'Portuguese' }, { value: 'ja', label: 'Japanese' }, { value: 'ko', label: 'Korean' }, { value: 'zh', label: 'Mandarin' }, { value: 'ru', label: 'Russian' }], description: '' },
        { name: 'speed', type: 'slider', label: 'Speed', default: 1.0, min: 0.5, max: 2.0, step: 0.1, description: 'Speech rate multiplier' },
      ],
    },
    stt: {
      type_id: 'stt', label: 'Speech-to-Text', category: 'speech', color: '#818CF8',
      description: 'Transcribe audio to text',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'text_out', type: 'text', required: false, description: '' }],
      config_fields: [
        { name: 'backend', type: 'select', label: 'Backend', default: 'whisper_local', options: [{ value: 'whisper_local', label: 'Whisper (Local)' }, { value: 'whisper_api', label: 'Whisper (API)' }, { value: 'deepgram', label: 'Deepgram' }], description: '' },
        { name: 'model_size', type: 'select', label: 'Model Size', default: 'base', options: [{ value: 'tiny', label: 'Tiny (fastest)' }, { value: 'base', label: 'Base' }, { value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large (best)' }], description: 'Whisper model size — larger = more accurate but slower' },
      ],
    },
    llm: {
      type_id: 'llm', label: 'LLM', category: 'llm', color: '#34D399',
      description: 'Request/response LLM (GPT-4o, Gemini, Claude, Ollama)',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: false, description: 'Audio input (multimodal)' },
        { name: 'text_in', type: 'text', required: false, description: 'Text input' },
      ],
      outputs: [
        { name: 'text_out', type: 'text', required: false, description: '' },
        { name: 'audio_out', type: 'audio', required: false, description: '' },
      ],
      config_fields: [
        { name: 'backend', type: 'select', label: 'Backend', default: 'openai:gpt-4o-audio-preview', options: [{ value: 'openai:gpt-4o-audio-preview', label: 'GPT-4o Audio' }, { value: 'openai:gpt-4o-mini-audio-preview', label: 'GPT-4o Mini Audio (~8B)' }, { value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini (~8B)' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'gemini:gemini-2.5-pro-preview-06-05', label: 'Gemini 2.5 Pro' }, { value: 'anthropic:claude-haiku-4-5-20251001', label: 'Claude Haiku' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'anthropic:claude-opus-4-6', label: 'Claude Opus' }, { value: 'ollama:llama3.1', label: 'Ollama — Llama 3.1 (8B)' }, { value: 'ollama:llama3.1:70b', label: 'Ollama — Llama 3.1 (70B)' }, { value: 'ollama:llama3.2', label: 'Ollama — Llama 3.2 (3B)' }, { value: 'ollama:llama3.2:1b', label: 'Ollama — Llama 3.2 (1B)' }, { value: 'ollama:mistral', label: 'Ollama — Mistral (7B)' }, { value: 'ollama:mixtral', label: 'Ollama — Mixtral (47B MoE)' }, { value: 'ollama:gemma2', label: 'Ollama — Gemma 2 (9B)' }, { value: 'ollama:gemma2:2b', label: 'Ollama — Gemma 2 (2B)' }, { value: 'ollama:phi3', label: 'Ollama — Phi-3 (3.8B)' }, { value: 'ollama:qwen2.5', label: 'Ollama — Qwen 2.5 (7B)' }, { value: 'ollama:qwen2.5:0.5b', label: 'Ollama — Qwen 2.5 (0.5B)' }, { value: 'ollama:deepseek-r1', label: 'Ollama — DeepSeek R1 (7B)' }, { value: 'ollama:deepseek-r1:70b', label: 'Ollama — DeepSeek R1 (70B)' }, { value: 'ollama:command-r', label: 'Ollama — Command R (35B)' }], description: "For Ollama, use 'ollama:<model>' for any model name" },
        { name: 'ollama_custom_model', type: 'string', label: 'Ollama Custom Model', default: '', description: "Override: type any Ollama model name (e.g. 'codellama:13b')" },
        { name: 'system_prompt', type: 'string', label: 'System Prompt', default: 'You are a helpful in-car voice assistant.', description: '' },
        { name: 'temperature', type: 'slider', label: 'Temperature', default: 0.7, min: 0, max: 2, step: 0.1, description: '' },
        { name: 'top_p', type: 'slider', label: 'Top P', default: 0.9, min: 0, max: 1, step: 0.05, description: 'Nucleus sampling threshold' },
        { name: 'top_k', type: 'slider', label: 'Top K', default: 40, min: 0, max: 200, step: 1, description: 'Top-k sampling (0=disabled)' },
        { name: 'max_tokens', type: 'number', label: 'Max Tokens', default: 256, description: 'Maximum output tokens (0=model default)' },
        { name: 'repeat_penalty', type: 'slider', label: 'Repeat Penalty', default: 1.1, min: 1, max: 2, step: 0.05, description: 'Repetition penalty' },
        { name: 'num_ctx', type: 'number', label: 'Context Length', default: 4096, description: 'Context window size (Ollama)' },
      ],
    },
    llm_realtime: {
      type_id: 'llm_realtime', label: 'LLM Realtime', category: 'llm', color: '#34D399',
      description: 'Streaming WebSocket LLM (OpenAI Realtime API)',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: 'Streaming audio' }],
      outputs: [
        { name: 'text_out', type: 'text', required: false, description: '' },
        { name: 'audio_out', type: 'audio', required: false, description: '' },
      ],
      config_fields: [
        { name: 'model', type: 'select', label: 'Model', default: 'gpt-4o-realtime-preview', options: [{ value: 'gpt-4o-realtime-preview', label: 'GPT-4o Realtime' }, { value: 'gpt-4o-mini-realtime-preview', label: 'GPT-4o Mini Realtime' }], description: '' },
        { name: 'voice', type: 'select', label: 'Voice', default: 'alloy', options: [{ value: 'alloy', label: 'Alloy' }, { value: 'echo', label: 'Echo' }, { value: 'shimmer', label: 'Shimmer' }, { value: 'ash', label: 'Ash' }, { value: 'coral', label: 'Coral' }, { value: 'sage', label: 'Sage' }], description: '' },
        { name: 'turn_detection', type: 'select', label: 'Turn Detection', default: 'server_vad', options: [{ value: 'server_vad', label: 'Server VAD' }, { value: 'manual', label: 'Manual' }], description: '' },
        { name: 'temperature', type: 'slider', label: 'Temperature', default: 0.8, min: 0, max: 2, step: 0.1, description: '' },
        { name: 'system_prompt', type: 'string', label: 'Instructions', default: 'You are a helpful in-car voice assistant.', description: '' },
      ],
    },
    telephony_codec: {
      type_id: 'telephony_codec', label: 'BT Codec', category: 'telephony', color: '#E879F9',
      description: 'Bluetooth codec simulation (CVSD narrowband / mSBC wideband)',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'codec_type', type: 'select', label: 'Codec', default: 'msbc', options: [{ value: 'cvsd', label: 'CVSD (8 kHz narrowband)' }, { value: 'msbc', label: 'mSBC (16 kHz wideband)' }, { value: 'none', label: 'None (bypass)' }], description: '' },
        { name: 'cvsd_snr_db', type: 'slider', label: 'CVSD SNR (dB)', default: 27, min: 20, max: 35, step: 1, description: 'Quantization noise floor for CVSD' },
        { name: 'msbc_snr_db', type: 'slider', label: 'mSBC SNR (dB)', default: 37, min: 30, max: 45, step: 1, description: 'Quantization noise floor for mSBC' },
      ],
    },
    aec: {
      type_id: 'aec', label: 'Echo Canceller', category: 'telephony', color: '#E879F9',
      description: 'Adaptive acoustic echo canceller (NLMS / RLS / Kalman)',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic signal (near-end + echo)' },
        { name: 'ref_in', type: 'audio', required: true, description: 'Far-end reference (speaker signal)' },
      ],
      outputs: [
        { name: 'audio_out', type: 'audio', required: false, description: 'Echo-cancelled signal' },
        { name: 'echo_est', type: 'audio', required: false, description: 'Estimated echo component' },
      ],
      config_fields: [
        { name: 'algorithm', type: 'select', label: 'Algorithm', default: 'nlms', options: [{ value: 'nlms', label: 'NLMS' }, { value: 'rls', label: 'RLS' }, { value: 'kalman', label: 'Kalman' }], description: '' },
        { name: 'filter_length_ms', type: 'slider', label: 'Filter Length (ms)', default: 200, min: 50, max: 500, step: 10, description: 'Adaptive filter tap length' },
        { name: 'step_size', type: 'slider', label: 'Step Size (mu)', default: 0.1, min: 0.01, max: 1, step: 0.01, description: 'NLMS learning rate' },
        { name: 'forgetting_factor', type: 'slider', label: 'Forgetting Factor', default: 0.999, min: 0.9, max: 1, step: 0.001, description: 'RLS lambda' },
      ],
    },
    aec_residual: {
      type_id: 'aec_residual', label: 'AEC Residual', category: 'telephony', color: '#E879F9',
      description: 'Simulate imperfect AEC: residual echo leakage + NLD artifacts',
      dynamic_inputs: false,
      inputs: [
        { name: 'mic_in', type: 'audio', required: true, description: 'Mic / AEC output signal' },
        { name: 'echo_ref', type: 'audio', required: false, description: 'Echo reference for residual' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'suppression_db', type: 'slider', label: 'Suppression (dB)', default: -25, min: -60, max: 0, step: 1, description: '-40=excellent AEC, -10=poor AEC' },
        { name: 'residual_type', type: 'select', label: 'Residual Type', default: 'mixed', options: [{ value: 'partial', label: 'Partial' }, { value: 'nonlinear', label: 'Non-linear (NLD)' }, { value: 'mixed', label: 'Mixed' }], description: '' },
        { name: 'nonlinear_distortion', type: 'slider', label: 'NLD Strength', default: 0.3, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    agc: {
      type_id: 'agc', label: 'AGC', category: 'telephony', color: '#E879F9',
      description: 'Automatic gain control with envelope follower and compression',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'preset', type: 'select', label: 'Preset', default: 'mild', options: [{ value: 'off', label: 'Off' }, { value: 'mild', label: 'Mild' }, { value: 'aggressive', label: 'Aggressive' }, { value: 'custom', label: 'Custom' }], description: '' },
        { name: 'target_rms_db', type: 'slider', label: 'Target RMS (dB)', default: -18, min: -30, max: 0, step: 1, description: '' },
        { name: 'attack_ms', type: 'slider', label: 'Attack (ms)', default: 50, min: 5, max: 500, step: 5, description: '' },
        { name: 'release_ms', type: 'slider', label: 'Release (ms)', default: 200, min: 20, max: 2000, step: 10, description: '' },
        { name: 'max_gain_db', type: 'slider', label: 'Max Gain (dB)', default: 30, min: 0, max: 40, step: 1, description: '' },
        { name: 'compression_ratio', type: 'slider', label: 'Compression Ratio', default: 4, min: 1, max: 20, step: 0.5, description: '' },
      ],
    },
    noise_reduction: {
      type_id: 'noise_reduction', label: 'Noise Reduction', category: 'telephony', color: '#E879F9',
      description: 'Speech enhancement via spectral subtraction or Wiener filtering',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: true, description: 'Noisy input' },
        { name: 'noise_ref', type: 'audio', required: false, description: 'Noise-only reference (optional)' },
      ],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'method', type: 'select', label: 'Method', default: 'spectral_subtraction', options: [{ value: 'spectral_subtraction', label: 'Spectral Subtraction' }, { value: 'wiener', label: 'Wiener Filter' }], description: '' },
        { name: 'suppression_db', type: 'slider', label: 'Max Suppression (dB)', default: 12, min: 0, max: 30, step: 1, description: '' },
        { name: 'noise_floor_db', type: 'slider', label: 'Noise Floor (dB)', default: -60, min: -80, max: -20, step: 1, description: '' },
        { name: 'smoothing_factor', type: 'slider', label: 'Smoothing', default: 0.9, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    sample_rate_converter: {
      type_id: 'sample_rate_converter', label: 'Sample Rate Converter', category: 'telephony', color: '#E879F9',
      description: 'Polyphase sample rate conversion',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'target_sample_rate', type: 'select', label: 'Target Rate', default: '16000', options: [{ value: '8000', label: '8 kHz (narrowband)' }, { value: '16000', label: '16 kHz (wideband)' }, { value: '22050', label: '22.05 kHz' }, { value: '44100', label: '44.1 kHz (CD)' }, { value: '48000', label: '48 kHz' }], description: '' },
      ],
    },
    time_delay: {
      type_id: 'time_delay', label: 'Time Delay', category: 'telephony', color: '#E879F9',
      description: 'Standalone delay line',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: '' }],
      config_fields: [
        { name: 'delay_ms', type: 'slider', label: 'Delay (ms)', default: 0, min: 0, max: 2000, step: 1, description: '' },
        { name: 'pad_mode', type: 'select', label: 'Mode', default: 'zero', options: [{ value: 'zero', label: 'Zero-pad (extends length)' }, { value: 'truncate', label: 'Truncate (maintain length)' }], description: '' },
      ],
    },
    doubletalk_metrics: {
      type_id: 'doubletalk_metrics', label: 'Doubletalk Metrics', category: 'telephony', color: '#E879F9',
      description: 'Compute ERLE, near-end distortion, and activity ratios',
      dynamic_inputs: false,
      inputs: [
        { name: 'near_end_clean', type: 'audio', required: true, description: 'Clean near-end reference' },
        { name: 'far_end_clean', type: 'audio', required: false, description: 'Clean far-end reference' },
        { name: 'mic_signal', type: 'audio', required: true, description: 'Mic signal (with echo)' },
        { name: 'aec_output', type: 'audio', required: false, description: 'AEC output signal' },
        { name: 'echo_ref', type: 'audio', required: false, description: 'Echo reference' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'frame_ms', type: 'slider', label: 'Frame Size (ms)', default: 20, min: 10, max: 40, step: 5, description: '' },
        { name: 'vad_threshold_db', type: 'slider', label: 'VAD Threshold (dB)', default: -40, min: -60, max: -20, step: 1, description: '' },
      ],
    },
    far_end_source: {
      type_id: 'far_end_source', label: 'Far-End Speech Source', category: 'sources', color: '#A3E635',
      description: 'Far-end caller audio with timing offset for 2-way telephony',
      dynamic_inputs: false,
      inputs: [],
      outputs: [{ name: 'audio_out', type: 'audio', required: false, description: 'Far-end speech signal' }],
      config_fields: [
        { name: 'source_mode', type: 'select', label: 'Source', default: 'pipeline_input', options: [{ value: 'pipeline_input', label: 'From Test Case' }, { value: 'corpus_entry', label: 'Corpus Entry' }, { value: 'file', label: 'Audio File' }], description: '' },
        { name: 'corpus_entry_id', type: 'string', label: 'Corpus Entry ID', default: '', description: '' },
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: '' },
        { name: 'level_db', type: 'slider', label: 'Level (dB)', default: 0, min: -30, max: 12, step: 0.5, description: 'Gain applied to far-end speech. 0=original level.' },
        { name: 'offset_ms', type: 'slider', label: 'Offset (ms)', default: 0, min: -5000, max: 5000, step: 50, description: 'Timing offset. Negative=far-end starts first (barge-in).' },
      ],
    },
    telephony_judge: {
      type_id: 'telephony_judge', label: 'Telephony Judge', category: 'evaluation', color: '#FB923C',
      description: 'LLM-based telephony quality evaluation with multi-judge voting',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: false, description: 'LLM response text' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Processed audio' },
        { name: 'near_end_ref', type: 'audio', required: false, description: 'Clean near-end reference' },
        { name: 'far_end_ref', type: 'audio', required: false, description: 'Clean far-end reference' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'modes', type: 'select', label: 'Evaluation Mode', default: 'auto', options: [{ value: 'auto', label: 'Auto-detect' }, { value: 'uplink_quality', label: 'Uplink Quality' }, { value: 'downlink_quality', label: 'Downlink Quality' }, { value: 'speaker_attribution', label: 'Speaker Attribution' }, { value: 'barge_in', label: 'Barge-in Detection' }, { value: 'conversational', label: 'Conversational Quality' }, { value: 'all', label: 'All Modes' }], description: '' },
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o-audio-preview', options: [{ value: 'openai:gpt-4o-audio-preview', label: 'GPT-4o Audio' }, { value: 'openai:gpt-4o-mini-audio-preview', label: 'GPT-4o Mini Audio' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }], description: '' },
        { name: 'num_judges', type: 'slider', label: 'Number of Judges', default: 3, min: 1, max: 7, step: 2, description: 'Odd number for majority voting' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'system_prompt_override', type: 'string', label: 'System Prompt Override', default: '', description: 'Override default telephony judge prompt' },
      ],
    },
    safety_critical_eval: {
      type_id: 'safety_critical_eval', label: 'Safety-Critical Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic safety evaluation: vehicle safety, personal safety, child safety, emergency protocol',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: 'Weighted average score threshold for pass' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: 'Any sub-agent below this = automatic fail' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: 'Original user query for context (optional)' },
      ],
    },
    compliance_eval: {
      type_id: 'compliance_eval', label: 'Compliance Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic compliance evaluation: legal, privacy, regulatory',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    trust_brand_eval: {
      type_id: 'trust_brand_eval', label: 'Trust & Brand Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic trust evaluation: misinformation, ethics/bias, brand safety',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    ux_quality_eval: {
      type_id: 'ux_quality_eval', label: 'UX Quality Eval', category: 'evaluation', color: '#FB923C',
      description: 'Agentic UX evaluation: driver cognitive load, emotional intelligence',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text to evaluate' },
        { name: 'audio_in', type: 'audio', required: false, description: 'Original audio (for context)' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'judge_backend', type: 'select', label: 'Judge LLM', default: 'openai:gpt-4o', options: [{ value: 'openai:gpt-4o', label: 'GPT-4o' }, { value: 'openai:gpt-4o-mini', label: 'GPT-4o Mini' }, { value: 'gemini:gemini-2.0-flash', label: 'Gemini 2.0 Flash' }, { value: 'anthropic:claude-sonnet-4-6', label: 'Claude Sonnet' }, { value: 'ollama:mistral', label: 'Ollama Mistral' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'weakest_link_threshold', type: 'slider', label: 'Weakest Link Threshold', default: 0.4, min: 0, max: 1, step: 0.05, description: '' },
        { name: 'user_query', type: 'string', label: 'User Query Context', default: '', description: '' },
      ],
    },
    eval_analysis: {
      type_id: 'eval_analysis', label: 'Evaluation & Analysis', category: 'evaluation', color: '#FB923C',
      description: 'Combined evaluation engine',
      dynamic_inputs: false,
      inputs: [
        { name: 'text_in', type: 'text', required: true, description: 'LLM response text' },
        { name: 'audio_in', type: 'audio', required: false, description: 'LLM response audio' },
      ],
      outputs: [{ name: 'eval_out', type: 'evaluation', required: false, description: '' }],
      config_fields: [
        { name: 'evaluators', type: 'select', label: 'Evaluators', default: 'command_match', options: [{ value: 'command_match', label: 'Command Match' }, { value: 'llm_judge', label: 'LLM Judge' }, { value: 'wer', label: 'WER' }, { value: 'all', label: 'All' }], description: '' },
        { name: 'pass_threshold', type: 'slider', label: 'Pass Threshold', default: 0.6, min: 0, max: 1, step: 0.05, description: '' },
      ],
    },
    router: {
      type_id: 'router', label: 'Router', category: 'logic', color: '#67E8F9',
      description: 'Route audio/text to one of N outputs based on a control signal',
      dynamic_inputs: false,
      inputs: [
        { name: 'audio_in', type: 'audio', required: false, description: 'Audio signal to route' },
        { name: 'text_in', type: 'text', required: false, description: 'Text signal to route' },
        { name: 'control', type: 'text', required: true, description: 'Route index (0, 1, 2, ... N-1)' },
      ],
      outputs: [
        ...Array.from({ length: 8 }, (_, i) => ({ name: `audio_out_${i}`, type: 'audio' as const, required: false, description: `Audio route ${i}` })),
        ...Array.from({ length: 8 }, (_, i) => ({ name: `text_out_${i}`, type: 'text' as const, required: false, description: `Text route ${i}` })),
      ],
      config_fields: [
        { name: 'num_routes', type: 'slider', label: 'Number of Routes', default: 2, min: 2, max: 8, step: 1, description: 'How many output routes (2-8)' },
        { name: 'default_route', type: 'number', label: 'Default Route', default: 0, description: 'Route index when control is missing or invalid' },
        { name: 'pass_silence', type: 'boolean', label: 'Pass Silence to Inactive', default: false, description: 'Send silence/empty to non-selected routes (vs nothing)' },
      ],
    },
    text_output: {
      type_id: 'text_output', label: 'Text Output', category: 'output', color: '#94A3B8',
      description: 'Display, save to file, or log text result',
      dynamic_inputs: false,
      inputs: [{ name: 'text_in', type: 'text', required: true, description: '' }],
      outputs: [],
      config_fields: [
        { name: 'label', type: 'string', label: 'Label', default: 'Output', description: '' },
        { name: 'output_mode', type: 'select', label: 'Output Mode', default: 'display', options: [{ value: 'display', label: 'Display in UI' }, { value: 'file', label: 'Write to File' }, { value: 'both', label: 'Display + File' }], description: '' },
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: 'Write output text to this file' },
        { name: 'output_dir', type: 'string', label: 'Output Directory', default: '', description: 'Write per-run output files here' },
        { name: 'file_format', type: 'select', label: 'File Format', default: 'txt', options: [{ value: 'txt', label: 'Plain Text (.txt)' }, { value: 'json', label: 'JSON (.json)' }, { value: 'csv', label: 'CSV (.csv)' }], description: '' },
      ],
    },
    audio_output: {
      type_id: 'audio_output', label: 'Audio Output', category: 'output', color: '#94A3B8',
      description: 'Play audio live, save to file, or both',
      dynamic_inputs: false,
      inputs: [{ name: 'audio_in', type: 'audio', required: true, description: '' }],
      outputs: [],
      config_fields: [
        { name: 'label', type: 'string', label: 'Label', default: 'Output', description: '' },
        { name: 'output_mode', type: 'select', label: 'Output Mode', default: 'display', options: [{ value: 'display', label: 'Display in UI' }, { value: 'file', label: 'Write to File' }, { value: 'audio_device', label: 'Play on Audio Device' }, { value: 'file_and_device', label: 'File + Audio Device' }, { value: 'all', label: 'Display + File + Device' }], description: '' },
        { name: 'file_path', type: 'string', label: 'File Path', default: '', description: 'Save audio to this WAV file' },
        { name: 'output_dir', type: 'string', label: 'Output Directory', default: '', description: 'Save per-run WAV files here' },
        { name: 'audio_device', type: 'string', label: 'Audio Device', default: 'default', description: "Audio output device name ('default' for system)" },
        { name: 'sample_rate', type: 'select', label: 'Output Sample Rate', default: '16000', options: [{ value: '8000', label: '8 kHz' }, { value: '16000', label: '16 kHz' }, { value: '22050', label: '22.05 kHz' }, { value: '44100', label: '44.1 kHz' }, { value: '48000', label: '48 kHz' }], description: '' },
      ],
    },
    eval_output: {
      type_id: 'eval_output', label: 'Eval Output', category: 'output', color: '#94A3B8',
      description: 'Display evaluation results',
      dynamic_inputs: false,
      inputs: [{ name: 'eval_in', type: 'evaluation', required: true, description: '' }],
      outputs: [],
      config_fields: [{ name: 'label', type: 'string', label: 'Label', default: 'Results', description: '' }],
    },
  },
}
